/**
 * Expo Push Notification Service
 * 
 * Uses Expo's push notification service instead of FCM directly.
 * Expo handles the APNs/FCM bridging automatically.
 * The APNs key generated by EAS is used by Expo's servers.
 */

const EXPO_PUSH_API = 'https://exp.host/--/api/v2/push/send';

/**
 * Send push notifications to a list of Expo push tokens.
 * Expo recommends sending in batches of 100.
 * @param {string[]} tokens - Array of Expo push tokens
 * @param {string} title - Notification title
 * @param {string} body - Notification body
 * @param {object} data - Extra data payload
 */
const sendPushNotifications = async (tokens, title, body, data = {}) => {
  if (!tokens || tokens.length === 0) {
    return { success: false, message: 'No tokens to send to' };
  }

  // Build messages array
  const messages = tokens.map(token => ({
    to: token,
    sound: 'default',
    title,
    body,
    data,
    priority: 'high',
    channelId: 'default',
  }));

  // Send in batches of 100 (Expo's recommendation)
  const batchSize = 100;
  const results = [];

  for (let i = 0; i < messages.length; i += batchSize) {
    const batch = messages.slice(i, i + batchSize);
    try {
      const response = await fetch(EXPO_PUSH_API, {
        method: 'POST',
        headers: {
          'Accept': 'application/json',
          'Accept-Encoding': 'gzip, deflate',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(batch),
      });
      const result = await response.json();
      results.push(result);
      console.log(`📨 Sent batch of ${batch.length} notifications`);
    } catch (err) {
      console.error('Push send error:', err.message);
      results.push({ error: err.message });
    }
  }

  return { success: true, results, totalSent: tokens.length };
};

module.exports = { sendPushNotifications };
